// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL2yhcRlkRre93saWTYoSyDDu0ZrGEvSM',
    appId: '1:705320477245:web:0d876e494ffb8878cf8054',
    messagingSenderId: '705320477245',
    projectId: 'loom-71386',
    authDomain: 'loom-71386.firebaseapp.com',
    storageBucket: 'loom-71386.firebasestorage.app',
    measurementId: 'G-NKBR32JBW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEuTtaQ6xZ9r1Hgkar9mjQQYcMtIKrqSg',
    appId: '1:705320477245:android:09cba1b8d717f74acf8054',
    messagingSenderId: '705320477245',
    projectId: 'loom-71386',
    storageBucket: 'loom-71386.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7zen2v0EPwQ7ru0jQMBnaONHoIXE-kiE',
    appId: '1:705320477245:ios:0941bad56f4094d6cf8054',
    messagingSenderId: '705320477245',
    projectId: 'loom-71386',
    storageBucket: 'loom-71386.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );
}
